route:
  name: Route
  description: Route an input to an output
  fields:
    output:
      required: true
    input:
      required: true

power_on:
  name: Power On TV
  description: Turn on TV via Neo CEC
  fields:
    output:
      required: true

power_off:
  name: Power Off TV
  description: Turn off TV via Neo CEC
  fields:
    output:
      required: true
