route:
  name: Route input
  description: Route an input to an output
  fields:
    output:
      required: true
    input:
      required: true

power_on:
  name: Power On Output

power_off:
  name: Power Off Output
